services:
  web:
    build: .
    container_name: film_review_api_day3
    ports:
      - "8000:8000"
    volumes:
      # Mount app folder into container for live reload during development
      - ./app:/app/app
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
