"""add is_deleted to films

Revision ID: 42eca7fb33fd
Revises: 77c7f9d14727
Create Date: 2026-10-05 04:50:57.063822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42eca7fb33fd'
down_revision: Union[str, Sequence[str], None] = '77c7f9d14727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'is_deleted')
    # ### end Alembic commands ###
