"""add hero to films

Revision ID: 77c7f9d14727
Revises: f1bfd0b4206b
Create Date: 2026-09-30 10:16:24.474400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c7f9d14727'
down_revision: Union[str, Sequence[str], None] = 'f1bfd0b4206b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('hero', sa.String(length=100), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'hero')
    # ### end Alembic commands ###
