from models import Country, Continent


COUNTRIES: list[Country] = [

    # # ==================== AFRICA ====================

    # Country(
    #     name="Nigeria",
    #     iso_code="NGA",
    #     population=206_000_000,
    #     area_km2=923_768.0,
    #     continent=Continent.AFRICA,
    #     languages=["English"],
    #     currency="NGN",
    #     neighbours=["BEN", "NER", "TCD", "CMR"],
    # ),
    # Country(
    #     name="Egypt",
    #     iso_code="EGY",
    #     population=104_000_000,
    #     area_km2=1_002_450.0,
    #     continent=Continent.AFRICA,
    #     languages=["Arabic"],
    #     currency="EGP",
    #     neighbours=["LBY", "SDN", "ISR"],
    # ),
    # Country(
    #     name="South Africa",
    #     iso_code="ZAF",
    #     population=59_000_000,
    #     area_km2=1_221_037.0,
    #     continent=Continent.AFRICA,
    #     languages=["Zulu", "Xhosa", "Afrikaans", "English"],
    #     currency="ZAR",
    #     neighbours=["NAM", "BWA", "ZWE", "MOZ", "LSO", "SWZ"],
    # ),
    # Country(
    #     name="Kenya",
    #     iso_code="KEN",
    #     population=53_700_000,
    #     area_km2=580_367.0,
    #     continent=Continent.AFRICA,
    #     languages=["Swahili", "English"],
    #     currency="KES",
    #     neighbours=["ETH", "SOM", "SSD", "UGA", "TZA"],
    # ),

    # ==================== ASIA ====================

    Country(
        name="India",
        iso_code="IND",
        population=1_380_000_000,
        area_km2=3_287_263.0,
        continent=Continent.ASIA,
        languages=["Hindi", "English"],
        currency="INR",
        neighbours=["PAK", "CHN", "NPL", "BTN", "BGD", "MMR"],
    ),
    Country(
        name="China",
        iso_code="CHN",
        population=1_410_000_000,
        area_km2=9_596_960.0,
        continent=Continent.ASIA,
        languages=["Mandarin"],
        currency="CNY",
        neighbours=["IND", "RUS", "MNG", "KAZ", "PAK", "NPL"],
    ),
    Country(
        name="Japan",
        iso_code="JPN",
        population=125_800_000,
        area_km2=377_975.0,
        continent=Continent.ASIA,
        languages=["Japanese"],
        currency="JPY",
        neighbours=[],
    ),
    Country(
        name="Indonesia",
        iso_code="IDN",
        population=273_500_000,
        area_km2=1_904_569.0,
        continent=Continent.ASIA,
        languages=["Indonesian"],
        currency="IDR",
        neighbours=["PNG", "TLS", "MYS"],
    ),

    # ==================== EUROPE ====================

    Country(
        name="Germany",
        iso_code="DEU",
        population=83_200_000,
        area_km2=357_386.0,
        continent=Continent.EUROPE,
        languages=["German"],
        currency="EUR",
        neighbours=["FRA", "POL", "CHE", "AUT", "CZE"],
    ),
    Country(
        name="France",
        iso_code="FRA",
        population=68_000_000,
        area_km2=551_695.0,
        continent=Continent.EUROPE,
        languages=["French"],
        currency="EUR",
        neighbours=["DEU", "ESP", "ITA", "BEL", "LUX", "CHE"],
    ),
    Country(
        name="Italy",
        iso_code="ITA",
        population=59_000_000,
        area_km2=301_340.0,
        continent=Continent.EUROPE,
        languages=["Italian"],
        currency="EUR",
        neighbours=["FRA", "CHE", "AUT", "SVN"],
    ),
    Country(
        name="Spain",
        iso_code="ESP",
        population=47_400_000,
        area_km2=505_990.0,
        continent=Continent.EUROPE,
        languages=["Spanish"],
        currency="EUR",
        neighbours=["FRA", "PRT"],
    ),

    # ==================== NORTH AMERICA ====================

    Country(
        name="United States",
        iso_code="USA",
        population=331_000_000,
        area_km2=9_833_517.0,
        continent=Continent.NORTH_AMERICA,
        languages=["English"],
        currency="USD",
        neighbours=["CAN", "MEX"],
    ),
    Country(
        name="Canada",
        iso_code="CAN",
        population=38_000_000,
        area_km2=9_984_670.0,
        continent=Continent.NORTH_AMERICA,
        languages=["English", "French"],
        currency="CAD",
        neighbours=["USA"],
    ),
    Country(
        name="Mexico",
        iso_code="MEX",
        population=128_900_000,
        area_km2=1_964_375.0,
        continent=Continent.NORTH_AMERICA,
        languages=["Spanish"],
        currency="MXN",
        neighbours=["USA", "GTM", "BLZ"],
    ),
    Country(
        name="Guatemala",
        iso_code="GTM",
        population=16_600_000,
        area_km2=108_889.0,
        continent=Continent.NORTH_AMERICA,
        languages=["Spanish"],
        currency="GTQ",
        neighbours=["MEX", "BLZ", "HND", "SLV"],
    ),

    # ==================== SOUTH AMERICA ====================

    Country(
        name="Brazil",
        iso_code="BRA",
        population=212_600_000,
        area_km2=8_515_767.0,
        continent=Continent.SOUTH_AMERICA,
        languages=["Portuguese"],
        currency="BRL",
        neighbours=["ARG", "BOL", "COL", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
    ),
    Country(
        name="Argentina",
        iso_code="ARG",
        population=45_400_000,
        area_km2=2_780_400.0,
        continent=Continent.SOUTH_AMERICA,
        languages=["Spanish"],
        currency="ARS",
        neighbours=["BRA", "BOL", "CHL", "PRY", "URY"],
    ),
    Country(
        name="Chile",
        iso_code="CHL",
        population=19_100_000,
        area_km2=756_102.0,
        continent=Continent.SOUTH_AMERICA,
        languages=["Spanish"],
        currency="CLP",
        neighbours=["ARG", "BOL", "PER"],
    ),
    Country(
        name="Peru",
        iso_code="PER",
        population=32_900_000,
        area_km2=1_285_216.0,
        continent=Continent.SOUTH_AMERICA,
        languages=["Spanish", "Quechua"],
        currency="PEN",
        neighbours=["BRA", "BOL", "CHL", "COL", "ECU"],
    ),

    # ==================== OCEANIA ====================

    Country(
        name="Australia",
        iso_code="AUS",
        population=25_700_000,
        area_km2=7_692_024.0,
        continent=Continent.OCEANIA,
        languages=["English"],
        currency="AUD",
        neighbours=[],
    ),
    Country(
        name="New Zealand",
        iso_code="NZL",
        population=5_200_000,
        area_km2=268_021.0,
        continent=Continent.OCEANIA,
        languages=["English", "Māori"],
        currency="NZD",
        neighbours=[],
    ),
    Country(
        name="Papua New Guinea",
        iso_code="PNG",
        population=8_900_000,
        area_km2=462_840.0,
        continent=Continent.OCEANIA,
        languages=["English", "Tok Pisin"],
        currency="PGK",
        neighbours=["IDN"],
    ),
    Country(
        name="Fiji",
        iso_code="FJI",
        population=896_000,
        area_km2=18_274.0,
        continent=Continent.OCEANIA,
        languages=["English", "Fijian", "Hindi"],
        currency="FJD",
        neighbours=[],
    ),

    # ==================== ANTARCTICA ====================

    Country(
        name="Antarctica",
        iso_code="ATA",
        population=0,
        area_km2=14_200_000.0,
        continent=Continent.ANTARCTICA,
        languages=[],
        currency="",
        neighbours=[],
    ),
    Country(
        name="Antarctic Research Zone",
        iso_code="ARZ",
        population=0,
        area_km2=3_000_000.0,
        continent=Continent.ANTARCTICA,
        languages=[],
        currency="",
        neighbours=[],
    ),
    Country(
        name="Ross Dependency",
        iso_code="RSD",
        population=0,
        area_km2=450_000.0,
        continent=Continent.ANTARCTICA,
        languages=[],
        currency="",
        neighbours=[],
    ),
    Country(
        name="Queen Maud Land",
        iso_code="QML",
        population=0,
        area_km2=2_700_000.0,
        continent=Continent.ANTARCTICA,
        languages=[],
        currency="",
        neighbours=[],
    ),
]


def get_countries() -> list[Country]:
    """Return a shallow copy of the in-memory country list."""
    return list(COUNTRIES)